// This file is generated by `npm run codegen` from
// ../lingo-backend/apps/api/openapi/openapi.v1.json
//
// Do not edit by hand. Run `npm run codegen` whenever the backend OpenAPI
// spec changes. CI runs `npm run codegen:check` to fail the build when this
// file drifts from the spec.
//
// Until the first `npm run codegen` is executed, no symbols are exported.

export {};
